### ISSUE TITLE
YM2151 Nuked OPM - Can't mute last channel

### ISSUE THREAD

**Issue by R4to0** [vgmrips/vgmplay-legacy#101]
I was messing with VGMPlay.ini and muting specific channels and noticed I can't mute channel 8 when using Nuked emulator type, MAME module isn't affected by this.

For example, I muted all channels in the chip like this:

```ini
[YM2151]
Disabled = False
; EmulatorType: 0 - MAME, 1 - Nuked OPM
EmulatorType = 0x01
; Channels: 8 (0-7)

MuteCh0 = true
MuteCh1 = true
MuteCh2 = true
MuteCh3 = true
MuteCh4 = true
MuteCh5 = true
MuteCh6 = true
MuteCh7 = true
```
but last channel still plays. I'm trying to find where this is applied but I'm not familiar with the code.

VGMPlay was compiled locally from master branch up to this post date.

**Comment by ValleyBell** [comment]
I had a quick look and there seems to be a typo here: https://github.com/vgmrips/vgmplay-legacy/blob/126eba226059e4c5ae4ffdf200d12a6ba03dc267/VGMPlay/chips/opm.c#L2132

It is supposed to be `<8` or `<=7`.

This is already fixed in vgmplay-libvgm.

**Comment by R4to0** [comment]
Yep that was it, worked just fine by changing to `< 8`.

**Comment by R4to0** [comment]
I opened a PR for this, if you don't mind to check.
