### ISSUE TITLE
Latest version?

### ISSUE THREAD

**Issue by Tasosgemah** [vgmrips/vgmplay-legacy#97]
I'm looking for the latest version of the in_vgm.dll and i randomly found v.0.51, last modified in 24-Nov-21, which is the latest i could find. However the last version released here seems to be 0.40.9, released 3 years before that but the latest commit is from May this year? Though there isn't any compiled version of that.

Which is the best dll file you can currently use, that's my question. Thanks in advance.

**Comment by ValleyBell** [comment]
Sorry, but this is the old/legacy VGMPlay and in_vgm.

A rewrite of both programs is in (unfortunately very slow) progress, as:
- https://github.com/ValleyBell/vgmplay-libvgm
- https://github.com/ValleyBell/in_vgm-libvgm

Those are at v0.51.0 now.

This repository is effectively in "maintenance" mode where I accept Pull requests, but no active work is done anymore.  
I just renamed the repo to "vgmplay-legacy" to reflect that.
